// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')


var chrome = require("selenium-webdriver/chrome");
var options = new chrome.Options();


describe('test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    // uncomment if you want the browser to close after test
    //await driver.quit();
  })
  it('test', async function() {
    login(driver);
  })
})

async function login(driver) {
  const fs = require('fs');
  let username;
  let password;
  // read contents of file 'login_info.txt' to get username and password
  fs.readFile('login_info.txt', 'utf8', function(err, contents) {
    if(err) { throw err; }
    console.log("processing file");
    let data = contents.toString();
    username = data.split('\n')[0];
    password = data.split('\n')[1];
    console.log(data);
  });
  await driver.get("https://drift--full.sandbox.my.salesforce.com/")
  await driver.manage().window().setRect({ width: 1280, height: 776 })
  await driver.findElement(By.id("username")).click()
  await driver.findElement(By.id("username")).sendKeys(username)
  await driver.findElement(By.id("password")).click()
  await driver.findElement(By.id("password")).sendKeys(password)
  await driver.findElement(By.id("Login")).click()
}